### ISSUE TITLE
Add a deployed version of the bot

### ISSUE THREAD

**Issue by Guryanov-Maksim** [Hexlet/react-flowbot-ui-kit#15]
На данный момент бота установить командой `npm install ...` невозможно. 
Можно собрать текущую реализацию бота и либо в реестр ее добавить (например, npm), либо прямо в репозитории ее выложить (например, в директории build) и устанавливать командой `npm install https://github.com/Hexlet/react-flowbot-ui-kit.git`.
@fey , @dzencot , как лучше сделать?

**Comment by fey** [comment]
Github позволяет деплоить страничку на github pages и на ней может быть шо угодно.
И работает это при пуше в определенную ветку `gh-pages` к примеру. Поэкспериментируйте, попробуйте

**Comment by Guryanov-Maksim** [comment]
Понял, спасибо, будем изучать.
